title = "Text-to-SQL Explorer"
connect_success="Connection to the PostgreSQL established successfully."
connect_failure="Connection to the PostgreSQL encountered and error."
subtitle="🔌 Connect to Your PostgreSQL Database"
caption="Securely enter your database URL to begin querying."